name: Build Test

on:
  push:
    # This workflow will run on every push to the main branch
    branches: [main]

jobs:
  build-test:
    name: Test Build Process
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Ensure this matches your project's Go version

      - name: Run Go Build
        # This step simply tests that the build can complete successfully without errors.
        # It does not create any final binaries or artifacts.
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o /dev/null
